- hosts: all
  tasks:
    - maven_artifact:
        group_id: com.maven.demo
        artifact_id: jenkins
        repository_url: 'http://host.docker.internal:8110/repository/nexus-repo/'
        username: admin
        password: November@2021
        dest: /download
